# Header
menu:
  主页: /
  标签: /tags
  归档: /archives
  关于: /about
  微博: /microblog
banner: "images/banner.jpg"

# Content
excerpt_link: 阅读全文
fancybox: true

# # Footer
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Footer
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use html like below...
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Sidebar
sidebar: right
widgets:
- oneword
- category
- tag
# - tagcloud
- archive
- recent_posts
- about
- nav-widget

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# Widget behavior
archive_type: 'monthly'
show_count: true
recent_posts_limits: 5

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId:  3W5Qm2qp5R7YCTWKTX9EeTph-gzGzoHsz
  appKey:  432mXjcNbVpYnasmPQ5QNiJC
  pageSize: 10 # comment list page size
  avatar: robohash # gravatar style https://valine.js.org/#/avatar
  placeholder: 快来留下评论吧～ # valine comment input placeholder(like: Please leave your footprints )
  
# mathjax
mathjax:
  enable: true
